development:
  adapter: postgresql
  encoding: unicode
  database: aws_whitepapers_tracker_development
  pool: 5
  username: stevenzeiler
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: aws_whitepapers_tracker_test
  pool: 5
  username: stevenzeiler
  host: localhost
